### ISSUE TITLE
Shouldn't use logging.exception()

### ISSUE THREAD

**Issue by hyperknot** [tkrajina/gpxpy#111]
In the parser.py file, there is a debug log and directly after, there is a `.exception` log:

https://github.com/tkrajina/gpxpy/blob/master/gpxpy/parser.py#L144-L145

This is actually raising an ERROR level log, triggering all kind exception watchers like Sentry, as well as polluting the logs for benign things. The first line is a `.debug()` line for a reason, I believe.

This is not how exceptions should be logged in Python. You can add them to the debug line, as listed here:
https://docs.python.org/2/library/logging.html#logging.Logger.debug

**Comment by hyperknot** [comment]
PR submitted: https://github.com/tkrajina/gpxpy/pull/112

**Comment by tkrajina** [comment]
Merged, thanks.
