### ISSUE TITLE
how to use "gpxinfo".  

### ISSUE THREAD

**Issue by PabloCuenca** [tkrajina/gpxpy#113]
Hi, i´m a newbie to Python, struggling to make use of gpxpy utility. 

First i import it into the main file with 
import gpxinfo

Then, I invoke gpxinfo.run and I try to pass a gpx file as an argument:
gpxinfo.run("D:\\Proyecto Balloon\codigo\Quijorna.gpx")

Resulting in the following error:
Traceback (most recent call last):
Error processing D
  File "D:\Proyecto Balloon\codigo\gpxinfo.py", line 117, in run
    gpx = mod_gpxpy.parse(open(gpx_file))
FileNotFoundError: [Errno 2] No such file or directory: 'D'
_________

I have tried other different options resulting also in other errors.

My ultimate goal is to extend "gpxinfo" so that it shows not only full track-segments statistics but also "per km" statistics.
Help is much appreciated.

**Comment by tkrajina** [comment]
gpxinfo is a command line tool, you run it with `python gpxinfo`, not import it. `gpxpy` is the library for import.
