### ISSUE TITLE
TZ Offset dropped

### ISSUE THREAD

**Issue by TomGoBravo** [tkrajina/gpxpy#114]
I opened a GPX file created by findmespot.com which contains "<time>2018-03-19T15:49:10-07:00</time>". I expected this to be parsed to UTC time 2018-03-19T22:49:10 but gpxpy 1.2.0 seems to drop the timezone offset. Looking at test.py in master I see test_remove_timezone_from_timestamp which seems to test for this behavior. parse_time in gpxpy/gpxfield.py explicitly drops the offset. Would you accept a patch to that file which uses the offset to return the UTC time for values in my GPX file?
Thanks,
Tom

**Comment by tkrajina** [comment]
You're right. ISO 8601 allows for TZ offsets, the library shouldn't just drop it. Yes, I'm willing to merge that fix.
