### ISSUE TITLE
exact distance?!?

### ISSUE THREAD

**Issue by jedie** [tkrajina/gpxpy#123]
I try to generate some gpx files for unittests...

To keep it simple, here's what I'm gonna do:

- use the circumference of the equator. This is 40075.017 kilometres (WGS 84)
- generate GPX data with `latitude=0` and `elevation=0`
- iterate the longitude based on the track length and `40075.017km / 360°`

Based on this i made a function to generate a GPX file and compare the distance... But i have some differences...

I generate a 10km long GPX tracks and get this:

```
real length...: 10000.0 m
gpxpy length..: 9982.1 m
Diff..........: 17.9 m
```

I generate a track that is "half the length of the earth equator" long and get this:

```
real length...: 20037.5 km
gpxpy length..: 20015.1 km
Diff..........: 22.4 km
```
The generates GPX looks like this:
```
<trkpt lat="0" lon="0">...</trkpt>
<trkpt lat="0" lon="1.0">...</trkpt>
<trkpt lat="0" lon="2.0">...</trkpt>
...
<trkpt lat="0" lon="179.0">...</trkpt>
<trkpt lat="0" lon="180.0">...</trkpt>
```

The full sources + the two gpx files are in gist, here:
- **test_gpx.py** -> https://gist.github.com/jedie/e86b3fc415e01e343bdecd8303c0d722#file-test_gpx-py
- **generated_10km.gpx** -> https://gist.github.com/jedie/e86b3fc415e01e343bdecd8303c0d722#file-generated_10km-gpx
- **half_equator.gpx** -> https://gist.github.com/jedie/e86b3fc415e01e343bdecd8303c0d722#file-half_equator-gpx

I also patch `gpxpy.geo.distance` and force to use and not use `gpxpy.geo.haversine_distance` but this doesn't really matter...

So i think my generation of longitude is simply wrong?!?
Any idea where i can get gpx test data with exact information about the content?

EDIT: Hm. I found https://www.j-berkemeier.de/ShowGPX.html and upload the generated GPX files. The distances there is exact the same as my "real length", e.g. from **half_equator.gpx**

![grafik](https://user-images.githubusercontent.com/71315/41610624-03239232-73ee-11e8-984e-f21eb90c4dc8.png)

So have i found a bug in gpxpy?!?

**Comment by snake-plissken** [comment]
Try it with this at the top of test_gpx.py, where you set the Earth's circumference:
```python
from gpxpy.gpx import GPX, GPXTrack, GPXTrackPoint, GPXTrackSegment
import math

earthCircumference = 2*math.pi*6371.0
km_per_longitude = earthCircumference / 360.0 
```

km per line of longitude using original Earth's circumference of 40075.017:
- 111.31949166666666

km per line of longitude using the Eath's circumference as calculated via 2*math.pi*6371.0
- 111.19492664455873

**Comment by jedie** [comment]
Sorry, i'm still inexperienced in his field :)

> earthCircumference = 2*math.pi*6371.0

So it's **40030.174km** 
The **6371.0** is the semi-major axis of the Earth in kilometers, isn't it?

But https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84 says Semi-major axis from WGS84 is defined as **6378.137 km**
Wouldn't it be better to do it that way: `2*math.pi*6378.137` than it's: **40075.017km**

And latitude/longitude in GPX files is always in WGS84 datum, as i can see here:

http://www.topografix.com/gpx/1/1/#type_latitudeType

I'm wrong?
