### ISSUE TITLE
probleme with adding extensions into gpx

### ISSUE THREAD

**Issue by CatTurbo** [tkrajina/gpxpy#128]
Hello
First thank you very much for the development of gpxpy, it helps really to work with gpx in my project. 
Actually I'm trying to some custom extension into an generated gpx file. But the extension doesn't appear into the generated file, although python doesn't give an error message. 
To test this bug, I've wrote a little programm which takes trackpoints from one file (test_import.gpx) and copy them to another (export.gpx) while trying to maintain the extensions of the original file. 

```
import gpxpy
import xml.etree.ElementTree as ET

gpx_file = open('test_import.gpx', 'r')
read_file = gpxpy.parse(gpx_file)

gpx = gpxpy.gpx.GPX()

gpx.extensions=read_file.extensions
gpx.nsmap=read_file.nsmap

for track in read_file.tracks:
    gpx_track = gpxpy.gpx.GPXTrack()
    #gpx_track.extensions = track.extensions
    #does work, give both extensions back

    gpx_track.extensions = track.extensions[1]
    #should in theory only add the first extension into the new file, but doesn't add one

    #gpx_track.extensions =  ET.fromstring('<locus:activity xmlns:locus="http://www.locusmap.eu">hiking</locus:activity>\n\t')
    #should in theory add the second extension into the new gpx file, but doesn't add one.
    for segment in track.segments:
        gpx_segment = gpxpy.gpx.GPXTrackSegment()

        for point in segment.points:
            gpx_segment.points.append(gpxpy.gpx.GPXTrackPoint(point.latitude, point.longitude, point.elevation))

        gpx_track.segments.append(gpx_segment)

    gpx.tracks.append(gpx_track)

with open("export.gpx", 'w', encoding="utf-8") as file:
    file.write(gpx.to_xml("1.1"))
```

The extensions used in the import file are:
```
<gpx_style:line>
	<gpx_style:color>0000FF</gpx_style:color>
	<gpx_style:opacity>0.59</gpx_style:opacity>
	<gpx_style:width>6.0</gpx_style:width>
</gpx_style:line>
<locus:activity>hiking</locus:activity>
```
After a little bit of testing I've found that the first extension (gpx:style) is allways copied to the new file, but the other one I need in my project (locus:activity) isn't copied, even if I try to copy also the namespace. Additionally I've tryed also to generate this extension manually (line with Et.fromstring), cause in my project I need to generate this extension specific to track which is generated. Unfortanetely I've failed here too, in the generated gpx file I don't find the locus:activity extension. 
The used version of python is 3.6.5, operating system is Windows 10, the used version of the gpxpy libary is the one from the dev branche, I've downloaded it one week ago. 
So maybe it is bug or maybe it is entirely my fault, cause I'm a beginner in python. Thank you very much for any help. 

[used_files.zip](https://github.com/tkrajina/gpxpy/files/2186266/used_files.zip)

**Comment by tkrajina** [comment]
Uf, this took me 45min to debug :( It really looked like a bug in gpxpy, but it's in your code. The problem is this line:

```
    gpx_track.extensions = track.extensions[1]
```

`extensions` must be a list, but you set it to be just one extension (the second one from the original gpx document).

This fixes your problem:

```
    gpx_track.extensions = [ track.extensions[1] ]
```

**Comment by CatTurbo** [comment]
Now it works perfect. 
Thank you very much for your help and sorry for have you bothered.
