### ISSUE TITLE
Uphill and Downhill time

### ISSUE THREAD

**Issue by raoramu** [tkrajina/gpxpy#131]
Sir/Madam, I used your repository https://github.com/tkrajina/gpxpy to read information from my GPX file. I am getting the Max speed, Avg speed, Total uphill, Total downhill, Started etc values correctly and along with that values I want additional values `time taken to Total uphill and Total downhill`. Please tell me how can I get these values. Please solve it for me or give a proper solution for it. Waiting for your reply.

**Comment by vmarceau** [comment]
Hello, 

I will be soon working on it along with issue #126 . I'll keep you informed here when its going to be implemented.

Best,
VM

**Comment by tkrajina** [comment]
Right, I'll close this issue as "duplicate".
