### ISSUE TITLE
desc filed in GPX file

### ISSUE THREAD

**Issue by nosorozec** [tkrajina/gpxpy#136]
Hello,

is it possible to use <desc> field in metadata of GPX file?
I try to gpx_obj.desc but it givers error; "AttributeError: GPX instance has no attribute 'desc'"

Rgds,
Konrad

PS. gpxpy is great!!!

**Comment by tkrajina** [comment]
The field is `gpx.description`, not `gpx.desc`. See the example in test.py: https://github.com/tkrajina/gpxpy/blob/master/test.py#L1761
