### ISSUE TITLE
to_xml() fails with an empty extension element

### ISSUE THREAD

**Issue by wrohdewald** [tkrajina/gpxpy#140]
The attached file is legal, IMHO. gpxpy can parse it but to_xml() fails:

  File "/home/wr/.local/lib/python3.6/site-packages/gpxpy/gpxfield.py", line 359, in _ETree_to_xml
    result.append(node.text.strip())
AttributeError: 'NoneType' object has no attribute 'strip'

The attached fix seems trivial. With this applied, to_xml() correctly  outputs the original data for my example.

[f0.txt](https://github.com/tkrajina/gpxpy/files/2358770/f0.txt)
[x.patch.txt](https://github.com/tkrajina/gpxpy/files/2358782/x.patch.txt)

**Comment by tkrajina** [comment]
Fixed, thanks!
