### ISSUE TITLE
coordinates at bounds/elevation_extremes

### ISSUE THREAD

**Issue by heitorPB** [tkrajina/gpxpy#144]
I want to extract some data from my gpx files such as:

- coordinates with lowest/highest elevation
- coordinates with lowest/highest lat/long

The methods `get_elevation_extremes()` returns only the lowest/highest elevation of the file, but not the coordinates where that happens. Something is similar to `get_bounds()` method, it returns 4 floats with the `GPXBounds`.

Is there any simple way to extract these coordinate points?

And by coordinates i mean something like `(lat, long, elevation, time)`.

**Comment by heitorPB** [comment]
@tkrajina, this feature was implemented? Could you provide some info about why this issue was closed?

**Comment by tkrajina** [comment]
There was no interest. That's all.
