### ISSUE TITLE
Use some kind of automated testing?

### ISSUE THREAD

**Issue by 1kastner** [tkrajina/gpxpy#153]
Would something like AppVeyor (see https://github.com/ogrisel/python-appveyor-demo) or Travis-CI (see https://github.com/pypa/python-manylinux-demo) be worthwhile looking at for this project?
I think the idea of automatically testing code as soon as it is merged is great. If you like, I might want to give it a try and you'll see a pull request somewhen soon.

**Comment by hugovk** [comment]
Travis CI already runs unit tests for PRs and merges:

https://github.com/tkrajina/gpxpy/blob/master/.travis.yml

https://travis-ci.org/tkrajina/gpxpy

**Comment by 1kastner** [comment]
Maybe it could also be done for the code of the readme file? Because I spotted yet another print-without-brackets. There are approaches like https://github.com/mrocklin/pymarkdown or https://github.com/jpsenior/sphinx-execute-code which could avoid having mixed Python 2 / 3 code on the very first page of the project :P

**Comment by hugovk** [comment]
> Maybe it could also be done for the code of the readme file? Because I spotted yet another print-without-brackets. There are approaches like [mrocklin/pymarkdown](https://github.com/mrocklin/pymarkdown) or [jpsenior/sphinx-execute-code](https://github.com/jpsenior/sphinx-execute-code) which could avoid having mixed Python 2 / 3 code on the very first page of the project :P

[mrocklin/pymarkdown](https://github.com/mrocklin/pymarkdown) says:

> _You should not use this project. You should use knitpy._

(See https://github.com/tkrajina/gpxpy/pull/164 to fix the `print`.)

**Comment by tkrajina** [comment]
If this is only about the code in the README files, there aren't that many code there. And most errors are those python2/python3 print statements which, once solved, are solved forewer.
