### ISSUE TITLE
Also test code inside readme file?

### ISSUE THREAD

**Issue by 1kastner** [tkrajina/gpxpy#154]
I found this nice discussion:
https://stackoverflow.com/questions/23250068/python-doctest-my-github-markdown-files

Maybe it could be part of the makefile?

**Comment by tkrajina** [comment]
Maybe, but it's also adding complexity for 20 lines of code (in the README) which almost never change. If somebody have a couple of minutes of time to help this project, better concentrate on bugs (https://github.com/tkrajina/gpxpy/issues?q=is%3Aissue+is%3Aopen+label%3Abug).
