### ISSUE TITLE
How to change output time format

### ISSUE THREAD

**Issue by BruceChastain** [tkrajina/gpxpy#163]
I would like to be able to select a different output format using gpxpy. For example when I use point.time, I get something like this: "2018-09-23 13:41:54", however I want it to be in a format like this: "2018, 9, 23, 13, 41, 54". Is this or could this be possible?

**Comment by Zverik** [comment]
`point.time` class is [datetime](https://docs.python.org/3.5/library/datetime.html), and you can format it however you like with `strftime`.
