### ISSUE TITLE
GPXTrackSegment.split() has a wrong docstring

### ISSUE THREAD

**Issue by wrohdewald** [tkrajina/gpxpy#165]
`    def split(self, point_no):
        """
        Splits the segment into two parts. If one of the split segments is
        empty it will not be added in the result. The segments will be split
        in place.

        Parameters
        ----------
        point_no : integer
            The index of the track point in the segment to split
        """
        part_1 = self.points[:point_no + 1]
        part_2 = self.points[point_no + 1:]
        return GPXTrackSegment(part_1), GPXTrackSegment(part_2)
`

**Comment by tkrajina** [comment]
Yes, it always returns two segments, regardless if one is empty or not. 
 Fixed in 4811c5c60e828b79bd524346f349241aa981146d
