### ISSUE TITLE
Unable to parse time with 9 decimals

### ISSUE THREAD

**Issue by TorbenDyrby** [tkrajina/gpxpy#174]
I have time with 9 decimals, e.g.
<time>2015-06-17T13:44:47.609273374Z</time>

I suggest the following change to gpxfield.py:
RE_TIMESTAMP = mod_re.compile(
    r'^([0-9]{4})-([0-9]{1,2})-([0-9]{1,2})[T ]([0-9]{1,2}):([0-9]{1,2}):([0-9]{1,2})'
    r'(\.[0-9]+)?(Z|[+-−][0-9]{2}:?(?:[0-9]{2})?)?$')

I know the remaining decimal(s) wont be used, but it is still better to be able to parse the time.

**Comment by tkrajina** [comment]
Fixed in https://github.com/tkrajina/gpxpy/commit/5255351600ffb48c17bc3e5ce7709ba0d58f1930 .
