### ISSUE TITLE
Time node is missing based on whitespace formatting

### ISSUE THREAD

**Issue by khargy** [tkrajina/gpxpy#179]
so if a trackpoint is formatted as follows:
```
			<trkpt lat="52.902352" lon="-118.099242">
				<ele>
					1195.06 
				</ele>
				<time>
					2018-09-19T14:17:17Z 
				</time>
			</trkpt>
```

The time node is lost. It seems like any whitespace before or after the time value will cause this issue
[Example.zip](https://github.com/tkrajina/gpxpy/files/3413870/Example.zip)

**Comment by tkrajina** [comment]
https://github.com/tkrajina/gpxpy/blob/dev/test.py#L745
