### ISSUE TITLE
python 2.7 syntax error

### ISSUE THREAD

**Issue by daurigi** [tkrajina/gpxpy#199]
Is there any reason why this shouldnt work on python 2.7?

  File "/home/xxxxx/Code/cuesheet/gpxpy/__init__.py", line 24
    def parse(xml_or_file: Union[AnyStr, IO[str]], version: Optional[str] = None) -> mod_gpx.GPX:
                         ^
SyntaxError: invalid syntax

**Comment by tkrajina** [comment]
To quote from the README:

> Gpxpy runs only with python 3.6+.

If you need python 2.7, you should use an older version.
