### ISSUE TITLE
Publish a pure Python wheel to PyPI?

### ISSUE THREAD

**Issue by jtpio** [tkrajina/gpxpy#237]
It looks like only the source distribution is uploaded to PyPI: https://pypi.org/project/gpxpy/1.4.2/#files

![image](https://user-images.githubusercontent.com/591645/131213755-eaacc98e-f2ec-40a0-b216-16539bb785e0.png)

It would be great to have a Python wheel uploaded there too. This will make it possible to use `gpxpy` with [pyodide](https://github.com/pyodide/pyodide) in the browser, for example when using [jupyterlite](https://github.com/jupyterlite/jupyterlite/).

Thanks!

**Comment by hugovk** [comment]
Please see PR https://github.com/tkrajina/gpxpy/pull/247.
