### ISSUE TITLE
Route issues

### ISSUE THREAD

**Issue by pramach** [tkrajina/gpxpy#238]
Hi
When working with **Routes** (e.g. from Garmin Basecamp), some important information are not accessible, e.g. like the trp:TransportationMode, the (planned) trp:DepartureTime or the trp:CalculationMode.

As per example:

>  <?xml version="1.0"?>
    <gpx xmlns="http://www.topografix.com/GPX/1/1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:wptx1="http://www.garmin.com/xmlschemas/WaypointExtension/v1" 
        xmlns:gpxtrx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" 
        xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1" 
        xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3" 
        xmlns:trp="http://www.garmin.com/xmlschemas/TripExtensions/v1" 
        xmlns:adv="http://www.garmin.com/xmlschemas/AdventuresExtensions/v1" 
        xmlns:prs="http://www.garmin.com/xmlschemas/PressureExtension/v1" 
        xmlns:tmd="http://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1" 
        xmlns:vptm="http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1" 
        xmlns:ctx="http://www.garmin.com/xmlschemas/CreationTimeExtension/v1" 
        xmlns:gpxacc="http://www.garmin.com/xmlschemas/AccelerationExtension/v1" 
        xmlns:gpxpx="http://www.garmin.com/xmlschemas/PowerExtension/v1" 
        xmlns:vidx1="http://www.garmin.com/xmlschemas/VideoExtension/v1" 
        creator="Garmin Desktop App" version="1.1" 
        xsi:schemaLocation="http://www.topografix.com/GPX/1/1 
        http://www.topografix.com/GPX/1/1/gpx.xsd http://www.garmin.com/xmlschemas/WaypointExtension/v1 
        http://www8.garmin.com/xmlschemas/WaypointExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/TrackPointExtension/v1 
        http://www.garmin.com/xmlschemas/TrackPointExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/GpxExtensions/v3 
        http://www8.garmin.com/xmlschemas/GpxExtensionsv3.xsd 
        http://www.garmin.com/xmlschemas/ActivityExtension/v1 
        http://www8.garmin.com/xmlschemas/ActivityExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/AdventuresExtensions/v1 
        http://www8.garmin.com/xmlschemas/AdventuresExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/PressureExtension/v1 
        http://www.garmin.com/xmlschemas/PressureExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/TripExtensions/v1 
        http://www.garmin.com/xmlschemas/TripExtensionsv1.xsd 
        http://www.garmin.com/xmlschemas/TripMetaDataExtensions/v1 
        http://www.garmin.com/xmlschemas/TripMetaDataExtensionsv1.xsd 
        http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensions/v1 
        http://www.garmin.com/xmlschemas/ViaPointTransportationModeExtensionsv1.xsd 
        http://www.garmin.com/xmlschemas/CreationTimeExtension/v1 
        http://www.garmin.com/xmlschemas/CreationTimeExtensionsv1.xsd 
        http://www.garmin.com/xmlschemas/AccelerationExtension/v1 
        http://www.garmin.com/xmlschemas/AccelerationExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/PowerExtension/v1 
        http://www.garmin.com/xmlschemas/PowerExtensionv1.xsd 
        http://www.garmin.com/xmlschemas/VideoExtension/v1 
        http://www.garmin.com/xmlschemas/VideoExtensionv1.xsd">
    <metadata>
        <link href="http://www.garmin.com">
            <text>Garmin International</text>
        </link>
        <time>2021-10-17T15:36:44Z</time>
        <bounds maxlat="55.294610979035497" maxlon="7.596380710601807" minlat="47.545213010162115" minlon="-10.379269123077393"/>
    </metadata>
    ...
    <rte>
    <name>GBR Hull - Liverpool - 307 km</name>
    <extensions>
      <gpxx:RouteExtension>
        <gpxx:IsAutoNamed>false</gpxx:IsAutoNamed>
        <gpxx:DisplayColor>Magenta</gpxx:DisplayColor>
      </gpxx:RouteExtension>
      <trp:Trip>
        <trp:TransportationMode>Motorcycling</trp:TransportationMode>
      </trp:Trip>
    </extensions>
    <rtept lat="53.743479866534472" lon="-0.273923529312015">
      <time>2021-10-11T06:45:48Z</time>
      <name>Rotterdam - Hull Ferry</name>
      <sym>Ferry</sym>
      <extensions>
        <trp:ViaPoint>
          <trp:DepartureTime>2021-10-06T23:00:39Z</trp:DepartureTime>
          <trp:CalculationMode>Shorter Distance</trp:CalculationMode>
          <trp:ElevationMode>Standard</trp:ElevationMode>
        </trp:ViaPoint>
        <gpxx:RoutePointExtension>
            ...
        </gpxx:RoutePointExtension>
      </extensions>
    </rtept>
    ...

Using Gpxpy 1.4.2 installed via pip on python 3.9 on OSX BigSur

Is there any possibility to get this Trip information too ?

An full example file can be provided on request.

**Comment by pramach** [comment]
Thanks again

When running your test code, I get 
>  [<Element '{http://www.garmin.com/xmlschemas/TripExtensions/v1}ViaPoint' at 0x7fa1e29f47c0>, <Element '{http://www.garmin.com/xmlschemas/GpxExtensions/v3}RoutePointExtension' at 0x7fa1c85bbe00>]
3
Traceback (most recent call last):
  File "/Users/WolfgangStuder/Documents/python/ws.GPX.out/ws.GPX.out/main.py", line 131, in button_click_action
    LoadTourData.load_tour_data(self)
  File "/Users/WolfgangStuder/Documents/python/ws.GPX.out/ws.GPX.out/modules/load_tour_data.py", line 27, in load_tour_data
    LoadTourData.load_tour_gpx(self, _selected_file)
  File "/Users/WolfgangStuder/Documents/python/ws.GPX.out/ws.GPX.out/modules/load_tour_data.py", line 94, in load_tour_gpx
    node = e.getchildren()[1]
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'`

I will do some further tests.

**Comment by tkrajina** [comment]
That error doesn't say that there are no children, just that `Element` has no `getchildren()` method. But note that the third line says `3` and that's `len(e)`. So there are children, you just need to iterate through them (without `getchildren`).
