### ISSUE TITLE
metadata error in bounds

### ISSUE THREAD

**Issue by ealaz** [tkrajina/gpxpy#246]
The metadata does not result in a valid xml file. Most codes will tolerate this but some (Garmin Homeport) will not, TYhe error is in bounds which has added space (linefeed). It can be corrected by modifying gpxfield.py as follows to remove the offending space & linefeed.
            if tag:
        if tag == 'bounds':
            if tag_open:
                body.append('>')
            body.append('</' + tag + '>')
            #print("tag,body:",tag,'\t',body)            
        else:
            if tag_open:
                body.append('>')
            body.append('\n' + indent + '</' + tag + '>')
It is inelegant but it works.

**Comment by tkrajina** [comment]
https://github.com/tkrajina/gpxpy/issues/186
