### ISSUE TITLE
Typo in __repr__ of SimpleTZ

### ISSUE THREAD

**Issue by Ephtolens** [tkrajina/gpxpy#269]
Hi !
Pb in this line -> https://github.com/tkrajina/gpxpy/blob/cad36d545f867aa1a219104b4b11c8ac10250e77/gpxpy/gpxfield.py#L74
Should be `f'SimpleTZ({self.tzname(None)}!r)'` instead of `'SimpleTZ({self.tzname(None}!r)'` I think

**Comment by tkrajina** [comment]
Fixed, thanks
