### ISSUE TITLE
reduce_points compares distances incorrectly

### ISSUE THREAD

**Issue by jonblack** [tkrajina/gpxpy#45]
I believe that the reduce_points algorithm incorrectly compares distances. The code you've written is the following:

    reduced_points = []
    for point in self.points:
        if reduced_points:
            distance = reduced_points[-1].distance_3d(point)
            if distance >= min_distance:
                reduced_points.append(point)
        else:
            # Leave first point:
            reduced_points.append(point)

    self.points = reduced_points

The first point is always kept. The distance between the first point and second point is compared to the threshold. If it's over the threshold, the second point is added. If not, the first point is compared to the third point. This is where the mistake is.

Measuring the distance from the first point to the third point doesn't follow the path, unless all the points follow a straight line. The best case is that the distance is longer than the accumulated distance following the path, and in the worst case, it stays under the threshold because the real path loops back close to another section of the track.

I'm not sure if this is the cause of the strange results I'm seeing, but when I take the following track...

![thun_1_raw](https://cloud.githubusercontent.com/assets/175080/7830069/f474177e-0448-11e5-8299-d9598b1e456c.png)

...and run `reduce_points(10)` on it, I get the following...

![thun_1_raw](https://cloud.githubusercontent.com/assets/175080/7830076/148fef74-0449-11e5-9416-a3e38aaa5738.png)

...which doesn't look correct. I'd love to know what your thoughts are on this.

You can find the GPX files in my repository here: https://github.com/jonblack/cmpgpx

**Comment by tkrajina** [comment]
Hey, sorry I forgot about this issue.

> If not, the first point is compared to the third point. This is where the mistake is.
>
> Measuring the distance from the first point to the third point doesn't follow the path, unless all the points follow a straight line.

Well, this is just one of the possible ways to "clean" the track. I'm not saying that it's the right way, but it also makes sense. If your track have points every 10cm, but you want them every 5m then this, I think, makes sense. Even for your track to me it makes sense, the only problem (looking to your images) is that  the treshold is too big -- but the basic shape of the track is preserved.

If you want to reduce the number of points in your track, but preserve the most characteristic part of its shape (i.e. remove points where the tracks points are in line, but preserve curves and extreemes) -- you should use the `simplify()` method. It will not indiscriminately remove points with a certain treshold of distance from the previous point but takes shape in account.
