### ISSUE TITLE
TypeError: argument of type 'builtin_function_or_method' is not iterable

### ISSUE THREAD

**Issue by rahulvgmail** [tkrajina/gpxpy#47]
could this be some missing library? (the file loads fine on the site you have hosted)

i will paste gpx file in comment.  

File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 423, in __parse_track_segment
    if self.xml_parser.get_node_name(child_node) == 'trkpt':
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 130, in get_node_name
    if '}' in node.tag:
TypeError: argument of type 'builtin_function_or_method' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/__init__.py", line 32, in parse
    return parser.parse()
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 219, in parse
    raise mod_gpx.GPXXMLSyntaxException('Error parsing XML: %s' % str(e), e)
gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: argument of type 'builtin_function_or_method' is not iterable

**Comment by rahulvgmail** [comment]
<?xml version="1.0"?>
<gpx version="1.0" creator="Ultra GPS Logger" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd">
<trk>
<name><![CDATA[AutoLog_Gangtok]]></name>
<trkseg>
<trkpt lat="27.337187" lon="88.618153"><ele>1842.00</ele><time>2014-11-05T23:20:52.203Z</time><speed>0.00</speed></trkpt><!-- acc:88.0 spd:0.0 bea:0.0 prv:gps [GPS] cmp:0.0 alt:1842.0::1842.0 cbt:false -->
<trkpt lat="27.337273" lon="88.618510"><ele>1831.00</ele><time>2014-11-05T23:20:58.168Z</time><speed>0.00</speed></trkpt><!-- acc:42.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:36.5 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337274" lon="88.618513"><ele>1831.00</ele><time>2014-11-05T23:21:03.200Z</time><speed>0.00</speed></trkpt><!-- acc:39.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:05 dst:0.3 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337243" lon="88.618400"><ele>1835.00</ele><time>2014-11-05T23:21:09.204Z</time><speed>0.00</speed></trkpt><!-- acc:30.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:11.7 cmp:0.0 alt:1835.0::1835.0 cbt:false -->
<trkpt lat="27.337249" lon="88.618419"><ele>1834.00</ele><time>2014-11-05T23:21:15.149Z</time><speed>0.00</speed></trkpt><!-- acc:17.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:2.0 cmp:0.0 alt:1834.0::1834.0 cbt:false -->
<trkpt lat="27.337256" lon="88.618441"><ele>1834.00</ele><time>2014-11-05T23:21:20.163Z</time><speed>0.00</speed></trkpt><!-- acc:15.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:05 dst:2.3 cmp:0.0 alt:1834.0::1834.0 cbt:false -->
<trkpt lat="27.337241" lon="88.618387"><ele>1835.00</ele><time>2014-11-05T23:21:25.202Z</time><speed>0.00</speed></trkpt><!-- acc:16.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:05 dst:5.6 cmp:0.0 alt:1835.0::1835.0 cbt:false -->
<trkpt lat="27.337246" lon="88.618408"><ele>1833.00</ele><time>2014-11-05T23:21:31.183Z</time><speed>0.00</speed></trkpt><!-- acc:19.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:2.2 cmp:0.0 alt:1833.0::1833.0 cbt:false -->
<trkpt lat="27.337257" lon="88.618450"><ele>1831.00</ele><time>2014-11-05T23:21:37.172Z</time><speed>0.00</speed></trkpt><!-- acc:17.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:4.4 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337257" lon="88.618450"><ele>1831.00</ele><time>2014-11-05T23:21:43.184Z</time><speed>0.00</speed></trkpt><!-- acc:19.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:0.1 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337257" lon="88.618451"><ele>1831.00</ele><time>2014-11-05T23:21:49.156Z</time><speed>0.00</speed></trkpt><!-- acc:17.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:0.1 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337258" lon="88.618453"><ele>1831.00</ele><time>2014-11-05T23:21:55.177Z</time><speed>0.00</speed></trkpt><!-- acc:15.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:06 dst:0.2 cmp:0.0 alt:1831.0::1831.0 cbt:false -->
<trkpt lat="27.337259" lon="88.618458"><ele>1830.00</ele><time>2014-11-05T23:22:00.204Z</time><speed>0.00</speed></trkpt><!-- acc:11.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:05 dst:0.5 cmp:0.0 alt:1830.0::1830.0 cbt:false -->

<trkpt lat="27.698786" lon="88.748768"><ele>2743.00</ele><time>2014-11-08T14:43:30.000Z</time><speed>0.00</speed></trkpt><!-- acc:28.0 spd:0.0 bea:0.0 prv:gps [GPS] dly:00:00:04 dst:0.0 cmp:0.0 alt:2743.0::2743.0 cbt:false -->
</trkseg>
</trk>
<wpt lat="27.337187" lon="88.618153"><ele>1842.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Start: Gangtok]]></name><desc><![CDATA[2014-11-06 04:50:51 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1842.0::1842.0 cbt:false -->
<wpt lat="27.337375" lon="88.618504"><ele>1804.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (1): 03:14:18]]></name><desc><![CDATA[2014-11-06 08:56:18 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1804.0::1804.0 cbt:false -->
<wpt lat="27.328474" lon="88.613031"><ele>1631.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (2): 00:17:24]]></name><desc><![CDATA[2014-11-06 09:48:00 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1631.0::1631.0 cbt:false -->
<wpt lat="27.328747" lon="88.612310"><ele>1624.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (3): 00:13:14]]></name><desc><![CDATA[2014-11-06 10:09:33 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1624.0::1624.0 cbt:false -->
<wpt lat="27.318662" lon="88.607607"><ele>1442.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (4): 00:11:25]]></name><desc><![CDATA[2014-11-06 11:03:15 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1442.0::1442.0 cbt:false -->
<wpt lat="27.329795" lon="88.612516"><ele>1588.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (5): 00:10:27]]></name><desc><![CDATA[2014-11-06 11:27:22 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1588.0::1588.0 cbt:false -->
<wpt lat="27.329414" lon="88.612309"><ele>1605.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (6): 00:22:26]]></name><desc><![CDATA[2014-11-06 12:10:18 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1605.0::1605.0 cbt:false -->
<wpt lat="27.329259" lon="88.612410"><ele>1650.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (7): 00:23:58]]></name><desc><![CDATA[2014-11-06 13:40:22 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1650.0::1650.0 cbt:false -->
<wpt lat="27.337555" lon="88.618639"><ele>1795.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (8): 09:31:16]]></name><desc><![CDATA[2014-11-06 23:37:52 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1795.0::1795.0 cbt:false -->
<wpt lat="27.337426" lon="88.618554"><ele>1816.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (9): 04:15:00]]></name><desc><![CDATA[2014-11-07 03:52:52 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1816.0::1816.0 cbt:false -->
<wpt lat="27.337368" lon="88.618699"><ele>1814.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (10): 03:06:21]]></name><desc><![CDATA[2014-11-07 06:59:14 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1814.0::1814.0 cbt:false -->
<wpt lat="27.337468" lon="88.618570"><ele>1809.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (11): 00:29:33]]></name><desc><![CDATA[2014-11-07 07:29:24 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1809.0::1809.0 cbt:false -->
<wpt lat="27.337460" lon="88.618470"><ele>1810.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (12): 00:15:51]]></name><desc><![CDATA[2014-11-07 07:47:08 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1810.0::1810.0 cbt:false -->
<wpt lat="27.337481" lon="88.618487"><ele>1806.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (13): 00:21:55]]></name><desc><![CDATA[2014-11-07 08:18:52 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1806.0::1806.0 cbt:false -->
<wpt lat="27.337500" lon="88.618532"><ele>1801.00</ele><time>1970-01-01T00:00:00.000Z</time><name><![CDATA[Gangtok (14): 01:08:48]]></name><desc><![CDATA[2014-11-07 09:32:46 GMT+05:30]]></desc></wpt><!-- acc:0.0 spd:0.0 bea:0.0 prv:AdvGPSPos [File] cmp:0.0 alt:1801.0::1801.0 cbt:false -->
<wpt lat="27.337332" lon="88.618651"><ele>1801.00</ele><time>2014-11-07T15:35:22.000Z</time><name><![CDATA[Gangtok (1): 00:25:37]]></name><desc><![CDATA[2014-11-07 21:30:59 GMT+05:30]]></desc></wpt><!-- acc:17.0 spd:0.5 bea:167.6 prv:gps [GPS] cmp:0.0 alt:1801.0::1801.0 cbt:false -->
<wpt lat="27.337452" lon="88.618733"><ele>1808.00</ele><time>2014-11-07T16:01:51.000Z</time><name><![CDATA[Gangtok (2): 10:52:18]]></name><desc><![CDATA[2014-11-08 08:24:10 GMT+05:30]]></desc></wpt><!-- acc:13.0 spd:1.0 bea:149.9 prv:gps [GPS] cmp:0.0 alt:1808.0::1808.0 cbt:false -->
<wpt lat="27.337332" lon="88.618669"><ele>1779.00</ele><time>2014-11-08T03:03:17.000Z</time><name><![CDATA[Gangtok (3): 02:12:22]]></name><desc><![CDATA[2014-11-08 10:45:41 GMT+05:30]]></desc></wpt><!-- acc:13.0 spd:0.0 bea:0.0 prv:gps [GPS] cmp:0.0 alt:1779.0::1779.0 cbt:false -->
<wpt lat="27.367969" lon="88.616464"><ele>1762.00</ele><time>2014-11-08T05:54:54.000Z</time><name><![CDATA[Gangtok (4): 00:17:29]]></name><desc><![CDATA[2014-11-08 11:42:21 GMT+05:30]]></desc></wpt><!-- acc:10.0 spd:2.75 bea:303.9 prv:gps [GPS] cmp:0.0 alt:1762.0::1762.0 cbt:false -->
<wpt lat="27.401816" lon="88.520979"><ele>573.00</ele><time>2014-11-08T08:01:27.000Z</time><name><![CDATA[Gangtok (5): 00:12:20]]></name><desc><![CDATA[2014-11-08 13:43:46 GMT+05:30]]></desc></wpt><!-- acc:15.0 spd:0.5 bea:243.2 prv:gps [GPS] cmp:0.0 alt:573.0::573.0 cbt:false -->
<wpt lat="27.515474" lon="88.582933"><ele>1394.00</ele><time>2014-11-08T09:54:43.000Z</time><name><![CDATA[Gangtok (6): 00:15:38]]></name><desc><![CDATA[2014-11-08 15:40:20 GMT+05:30]]></desc></wpt><!-- acc:3.0 spd:0.25 bea:23.2 prv:gps [GPS] cmp:0.0 alt:1394.0::1394.0 cbt:false -->
<wpt lat="27.543047" lon="88.628409"><ele>1280.00</ele><time>2014-11-08T10:43:27.000Z</time><name><![CDATA[Gangtok (7): 00:11:10]]></name><desc><![CDATA[2014-11-08 16:24:36 GMT+05:30]]></desc></wpt><!-- acc:12.0 spd:1.5 bea:130.5 prv:gps [GPS] cmp:0.0 alt:1280.0::1280.0 cbt:false -->
<wpt lat="27.698578" lon="88.748834"><ele>2751.00</ele><time>2014-11-08T12:47:03.000Z</time><name><![CDATA[Gangtok (8): 00:27:44]]></name><desc><![CDATA[2014-11-08 18:44:47 GMT+05:30]]></desc></wpt><!-- acc:11.0 spd:0.0 bea:0.0 prv:gps [GPS] cmp:0.0 alt:2751.0::2751.0 cbt:false -->
<wpt lat="27.698714" lon="88.748771"><ele>2765.00</ele><time>2014-11-08T13:14:47.000Z</time><name><![CDATA[Gangtok (9): 01:28:43]]></name><desc><![CDATA[2014-11-08 20:13:30 GMT+05:30]]></desc></wpt><!-- acc:16.0 spd:0.0 bea:0.0 prv:gps [GPS] cmp:0.0 alt:2765.0::2765.0 cbt:false -->
<wpt lat="27.698786" lon="88.748768"><ele>2743.00</ele><time>2014-11-08T14:43:30.000Z</time><name><![CDATA[Stop: Gangtok]]></name><desc><![CDATA[2014-11-08 20:13:30 GMT+05:30]]></desc></wpt><!-- acc:28.0 spd:0.0 bea:0.0 prv:gps [GPS] cmp:0.0 alt:2743.0::2743.0 cbt:false -->
</gpx>
<!-- Summary -->
<!-- Creator: Ultra GPS Logger 3.098a -->
<!-- Name: AutoLog_Gangtok -->
<!-- Duration: 15:24:16 -->
<!-- Length: 125585.97 -->
<!-- Speed: 1.98 -->
<!-- POI: 25 -->
<!-- Category:  -->
<!-- From: 27.33718675; 88.61815327 To: 27.69878605; 88.74876781 -->
<!-- FromCity: Gangtok ToCity: Gangtok -->
<!-- FromUTC: 2014-11-05T23:19:14Z [5.0] ToUTC: 2014-11-08T14:43:30Z [5.0] -->
<!-- Trigger: 105 TimeTrigger: 1000 DistTrigger: 0 -->

**Comment by rahulvgmail** [comment]
Full Stack Trace

 gpx_file = open('/vagrant/data/2014-11-06_044915_AutoLog_Gangtok (copy).gpx', 'r')
>>> gpx= gpxpy.parse(gpx_file)
ERROR:root:argument of type 'builtin_function_or_method' is not iterable
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 204, in parse
    self.__parse_dom()
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 254, in __parse_dom
    self.gpx.tracks.append(self.__parse_track(node))
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 413, in __parse_track
    track_segment = self.__parse_track_segment(child_node)
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 423, in __parse_track_segment
    if self.xml_parser.get_node_name(child_node) == 'trkpt':
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 130, in get_node_name
    if '}' in node.tag:
TypeError: argument of type 'builtin_function_or_method' is not iterable
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 204, in parse
    self.__parse_dom()
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 254, in __parse_dom
    self.gpx.tracks.append(self.__parse_track(node))
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 413, in __parse_track
    track_segment = self.__parse_track_segment(child_node)
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 423, in __parse_track_segment
    if self.xml_parser.get_node_name(child_node) == 'trkpt':
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 130, in get_node_name
    if '}' in node.tag:
TypeError: argument of type 'builtin_function_or_method' is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/__init__.py", line 32, in parse
    return parser.parse()
  File "/home/vagrant/.virtualenvs/trip2/lib/python3.4/site-packages/gpxpy/parser.py", line 219, in parse
    raise mod_gpx.GPXXMLSyntaxException('Error parsing XML: %s' % str(e), e)
gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: argument of type 'builtin_function_or_method' is not iterable

**Comment by LP1LP** [comment]
TypeError: argument of type 'builtin_function_or_method' is not iterable
