### ISSUE TITLE
Error on gpx 1.0 format parsing because of <course> float value

### ISSUE THREAD

**Issue by eneiluj** [tkrajina/gpxpy#51]
Hi,

Thanks a lot for gpxpy that i use a lot.

I noticed there was a possible mistake in the parsing about the value of "course" tags. The GPX 1.0 format (http://www.topografix.com/gpx_manual.asp) tells us its unit is degrees, so in other words, a float. But the gpxpy parser apparently tries to read it as an int.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gpxpy/__init__.py", line 34, in parse
    return parser.parse()
  File "/usr/local/lib/python2.7/dist-packages/gpxpy/parser.py", line 211, in parse
    raise mod_gpx.GPXXMLSyntaxException('Error parsing XML: %s' % str(e), e)
gpxpy.gpx.GPXXMLSyntaxException: Error parsing XML: Invalid value for <course>... 67.72383 (invalid literal for int() with base 10: '67.72383')
```

Apparently the "course" tag is not included anymore in GPX 1.1 (last implementation) but there are still lots of programs producing GPX 1.0 files.

Do you agree with me that "course" values should be red as floats in gpxpy ?

**Comment by tkrajina** [comment]
Yes, I think you're right. 

I pushed a fix which should make `<course>` a float value in https://github.com/tkrajina/gpxpy/tree/course-float. Let me know if it is OK.

**Comment by eneiluj** [comment]
Thanks a lot ! It's working.
