### ISSUE TITLE
Missing CDATA while exporting gpx

### ISSUE THREAD

**Issue by JaniszM** [tkrajina/gpxpy#52]
Using gpx.to_xml() misses CDATA marks in tags, e.g:
original file: `<name><![CDATA[Ślad zapisany przez OSMTracker - Android™]]></name>`
after calling to_xml(): `<name>Ślad zapisany przez OSMTracker - Android™</name>`

This can cause real problems :)

**Comment by tkrajina** [comment]
Yes, you're right, thanks! I somehow overlooked this when rewriting it to work with gpx1.1.

I think that this https://github.com/tkrajina/gpxpy/commit/98276b7e17730638cf747af09d9994d09853f45f should fix your problem(s). It encodes the value of XML tags (not exactly adding `CDATA`), but it should fix your problem. 

Can you try if it works for you?

**Comment by JaniszM** [comment]
Hmm, I dont have much time now, and I can't check this commit now. If you are encoding values according to xml encoding all should be ok. However If xml contains CDATA if should be simply exported :)

I have some work to do, soon I should finish it and I will let you know if this is big problem for me ;)
