### ISSUE TITLE
Empty tags not cleaned.

### ISSUE THREAD

**Issue by rhn** [tkrajina/gpxpy#67]
After creating a basic file/track/segment/point, empty tags appear in the output. This only affects tags which contain other tags.
It seems to come from the fact that they are harcoded in gpx_1_1_fields. There seems to be a way to avoid it by letting the field contain its children (like the "extensions" field), but I wasn't able to quickly figure out how to make child tags available as attributes on the same object as parent.

**Comment by tkrajina** [comment]
Yes, you are right. I noticed that after a1558e3c94aa11689d690658ae0c608dc6073501 and this is one of the reasons why I didn't release a new version yet. I'm not sure when I'll have the time to fix that, but if it's urgent to you (and you still want to use the latest `master`) I think that reverting that commit is a temporary fix.

**Comment by tkrajina** [comment]
Update, now that I checked that commit I figured out that the problem for `extensions` is easier than I thought. It should be fixed with 4bc6c152c1a8484442a0339376f82677590fc73d. I don't have the time to test other complex fields now, but will probably do in the next few days.
