### ISSUE TITLE
Please sign source tarballs

### ISSUE THREAD

**Issue by Natureshadow** [tkrajina/gpxpy#75]
Hi,

I am packaging gpxpy for Debian. It would be great if you could gpg-sign your tarballs uploaded to PyPI from the next release.

Cheers,
Nik

**Comment by tkrajina** [comment]
Hi,

I think it should be OK with https://github.com/tkrajina/gpxpy/commit/81a9857d55f079bfe6873bb45c3a0729bbc5f619 . I just released 1.1.2, let me know if it's OK.

tk

**Comment by Natureshadow** [comment]
Looks good, thanks!
