### ISSUE TITLE
AttributeError: 'set' object has no attribute 'items' when using gpx.to_xml() with version 1.1

### ISSUE THREAD

**Issue by aayaffe** [tkrajina/gpxpy#76]
Following this stackoverflow question: [http://stackoverflow.com/questions/39993739/gpxpy-not-outputting-extensions-in-to-xml/](url)

### When using gpx.to_xml(varsion="1.1") the following stack trace is received (no error with version 1.0):

> Traceback (most recent call last):
>   File "C:/programing/GPXConverter/forstack.py", line 14, in <module>
>     print(gpx.to_xml(version="1.1"))
>   File "C:\Users\aayaffe\AppData\Local\Programs\Python\Python35\lib\site-packages\gpxpy\gpx.py", line 2594, in to_xml
>     content = mod_gpxfield.gpx_fields_to_xml(self, 'gpx', version, custom_attributes=xml_attributes)
>   File "C:\Users\aayaffe\AppData\Local\Programs\Python\Python35\lib\site-packages\gpxpy\gpxfield.py", line 312, in gpx_fields_to_xml
>     xml_value = gpx_field.to_xml(value, version)
>   File "C:\Users\aayaffe\AppData\Local\Programs\Python\Python35\lib\site-packages\gpxpy\gpxfield.py", line 192, in to_xml
>     result += gpx_fields_to_xml(obj, self.tag, version)
>   File "C:\Users\aayaffe\AppData\Local\Programs\Python\Python35\lib\site-packages\gpxpy\gpxfield.py", line 312, in gpx_fields_to_xml
>     xml_value = gpx_field.to_xml(value, version)
>   File "C:\Users\aayaffe\AppData\Local\Programs\Python\Python35\lib\site-packages\gpxpy\gpxfield.py", line 269, in to_xml
>     for ext_key, ext_value in value.items():
> AttributeError: 'set' object has no attribute 'items'

### Code used:
`import xml.etree.ElementTree
import gpxpy.gpx
f = xml.etree.ElementTree.parse('stack.gpx')
gpx = gpxpy.gpx.GPX()
gpx.creator = "a"
odpoint = f.find("{http://www.opencpn.org}path").find("{http://www.opencpn.org}ODPoint")
w1 = gpxpy.gpx.GPXWaypoint()
w1.latitude = odpoint.attrib.get('lat')
w1.longitude = odpoint.attrib.get('lon')
w1.extensions = {odpoint.find('{http://www.opencpn.org}guid')}
w1.type = 'WPT'
gpx.waypoints.append(w1)
print(gpx.to_xml(version="1.1"))`

### GPX file used:
`<?xml version="1.0"?>
<OCPNDraw version="0.1" creator="OpenCPN" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:opencpn="http://www.opencpn.org">
  <opencpn:path>
    <opencpn:type>Boundary</opencpn:type>
    <opencpn:ODPoint lat="47.0" lon="59.0">
      <opencpn:type>Boundary Point</opencpn:type>
      <opencpn:guid>4fbfffff-806d-4317-b245-4e6e2d190000</opencpn:guid>
    </opencpn:ODPoint>
  </opencpn:path>
</OCPNDraw>
`

**Comment by tkrajina** [comment]
Yes, I see.

I must investigate further to see why this happens, but in the meantime you can use this quickfix: https://github.com/tkrajina/gpxpy/commit/0afc794e5ec1f27b28f82e49b79f1c0295d438bc

**Comment by tkrajina** [comment]
Ah, now I see. The problem is this line:

    w1.extensions = {odpoint.find('{http://www.opencpn.org}guid')}

the `extensions` attribute must be a dictionary. You defined it as a set.
