### ISSUE TITLE
output is not reproducible

### ISSUE THREAD

**Issue by wrohdewald** [tkrajina/gpxpy#78]
Python3, gpxpy 1.1.1 (installed today with pip3)

the header xml fields have random order. It would be nice always having the same order:

- md5sum would tell me that the content did not change
- saving output in a git archive would not cause unwanted commits

@@ -1,5 +1,5 @@
 <?xml version="1.0" encoding="UTF-8"?>
-<gpx xmlns="http://www.topografix.com/GPX/1/0" xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" creator="gpx.py -- https://github.com/tkrajina/gpxpy">
+<gpx xsi:schemaLocation="http://www.topografix.com/GPX/1/0 http://www.topografix.com/GPX/1/0/gpx.xsd" xmlns="http://www.topografix.com/GPX/1/0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.0" creator="gpx.py -- https://github.com/tkrajina/gpxpy">

**Comment by tkrajina** [comment]
Yes, I'm aware of this problem.

I just pushed a quickfix for this here: https://github.com/tkrajina/gpxpy/commit/75381dbd3f46d915160485d4eb7b9b71519da03a

It will sort the attributes each time if there is more than one attribute.

Now, this has a small performance penalty and it works only with python2. I'll try to think for a better idea. Of course, suggestions are welcome.

**Comment by wrohdewald** [comment]
how about using OrderedDict? It exists since Python 2.7

--- a/gpxpy/gpx.py
+++ b/gpxpy/gpx.py
@@ -2582,11 +2582,11 @@ class GPX:
             self.creator = 'gpx.py -- https://github.com/tkrajina/gpxpy'
 
         v = version.replace('.', '/')
-        xml_attributes = {
-                'xmlns:xsi': 'http://www.w3.org/2001/XMLSchema-instance',
-                'xmlns': 'http://www.topografix.com/GPX/%s' % v,
-                'xsi:schemaLocation': 'http://www.topografix.com/GPX/%s http://www.topografix.com/GPX/%s/gpx.xsd' % (v, v)
-        }
+        xml_attributes = mod_collections.OrderedDict([
+                ('xmlns:xsi', 'http://www.w3.org/2001/XMLSchema-instance'),
+                ('xmlns', 'http://www.topografix.com/GPX/%s' % v),
+                ('xsi:schemaLocation', 'http://www.topografix.com/GPX/%s http://www.topografix.com/GPX/%s/gpx.xsd' % (v, v))
+        ])
 
         content = mod_gpxfield.gpx_fields_to_xml(self, 'gpx', version, custom_attributes=xml_attributes)

**Comment by tkrajina** [comment]
Yes, it makes sense. Although, now that I look at it, the `custom_attributes` named parameter is used only once, so even the `dict.sort()` wouldn't be such a problem.  But, on the other side, there is no `sort()` for `{}.items()` in py3. And if `OrderedDict` is the only reason to break py2.6, I'll just *not* sort but expect the attrs to be a list:

https://github.com/tkrajina/gpxpy/commit/8abebcad9232ad97df929a4e604011fb7be4d46b

...and it will work everywhere.
