### ISSUE TITLE
gpxpy writes logs in the root logger

### ISSUE THREAD

**Issue by stac47** [tkrajina/gpxpy#79]
Hello,

I spotted that throughout the library, the logs are written in the ROOT logger. This is not really convenient if an application using this library wants to redirect the logs to another file.

I would propose to define a default logger for the gpxpy library and prevent writing logs by default as explained here https://docs.python.org/3/howto/logging.html#library-config.

If you think it is worth taking some time to do it, just tell me and I will provide a PR.
Regards,
Stac

**Comment by tkrajina** [comment]
Hi Laurent,

Agreed, this is a good idea. If you want to implement it, I'd definitely be interested in merging the PR.

**Comment by tkrajina** [comment]
Closing, but if somebody wants this feature I'm still interested in a PR.
