### ISSUE TITLE
variable formatting of output

### ISSUE THREAD

**Issue by wrohdewald** [tkrajina/gpxpy#80]
I am no friend of all those GPX GUI utilities, I prefer directly editing the gpx. One of my needs is removing unwanted trackpoints (like when forgetting to stop recording before driving back home).

That is much easier if there is exactly one line per trackpoint.

My bad hack is to do

gpxpy.utils.to_xml = to_xml

where to_xml is my own implementation starting with
    if tag in ('ele', 'time'):
        result = '<%s' % tag
    else:
        result = '\n<%s' % tag

Of course this is bad -
it depends of implementation details
it should probably respect more tags but those are the two I am currently outputting

It would be nice if I could pass a list of tag names which gpxpy should not prepend with a LF.

**Comment by tkrajina** [comment]
Maybe a better solution would be to have an optional param telling the `to_xml()` function to pretty-format the xml file.

**Comment by wrohdewald** [comment]
Maybe OR-able flags like
-indent
-separate line per closing tag
-one line per trackpoint (has precedence over line per closing tag)
-CRLF

to_xml ( INDENT | ONELINEPERTRACKPOINT)

**Comment by tkrajina** [comment]
Well, I agree with you that it would be nice. But on the other side it creates some complexity which I need to take care in the future, and it's not a super-important feature (in 6 years, only you asked for this). Even formatting the XML can easily be done in a script after calling `to_xml()` but I think this is something more people will use than having newlines in front of some specific tags.

**Comment by wrohdewald** [comment]
Meanwhile I found a cleaner solution:

def to_xml(tag, attributes=None, content=None, default=None, escape=False):
    result = org_to_xml(tag, attributes, content, default, escape)
    tag = result.split('>')[0]
    if tag[:2] == '\n<' and tag[2:] in ('ele', 'time'):
        result = result[1:]
    return result

org_to_xml = gpxpy.utils.to_xml

gpxpy.utils.to_xml = to_xml
