### ISSUE TITLE
UnicodeWarning in recent release

### ISSUE THREAD

**Issue by hyperknot** [tkrajina/gpxpy#84]
Under Python 2.7, I'm getting the following warning in the recent release:

```
gpxpy/parser.py:168: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
```

**Comment by tkrajina** [comment]
I think this should fix it: 456c27ac6eaa81242b24c710730ea078756ef5dc . Can you try it?

**Comment by hyperknot** [comment]
Why [:4] instead of [:3]?

**Comment by tkrajina** [comment]
You clicked too early. I fixed that a few seconds later :)

PS. If you really want the reason... It's totally stupid, I have tmux using `ctrl+a` to switch between windows. But if I use vim in tmux and the cursor is on a number, then `ctrl+a` increases a number. And that's what happened :)

**Comment by hyperknot** [comment]
I'll be able to test it in the evening, but are you sure this works in
Python 3? AFAIK there is no unicode there.

**Comment by tkrajina** [comment]
I know (https://travis-ci.org/tkrajina/gpxpy/builds/207847788). That's why I didn't commit it in master but in a temporary branch.

**Comment by hyperknot** [comment]
maybe the fix is as simple as either putting a u at the string or using
startswith?




On 2017. Mar 5., Sun at 17:23, Tomo Krajina <notifications@github.com> wr

**Comment by hyperknot** [comment]
I did a PR for this, using startswith and 'u':
https://github.com/tkrajina/gpxpy/pull/87

**Comment by hyperknot** [comment]
@tkrajina why is this line `utf-7`? Any possibility of a tmux + vim bug?
https://github.com/tkrajina/gpxpy/blob/2d965f3aa8692f2cac6a5ae4bfda98078aa268ec/test.py#L108

**Comment by hyperknot** [comment]
New try here:
https://github.com/tkrajina/gpxpy/pull/90
