### ISSUE TITLE
class GPXWaypoint: __init__ is missing some GPX parameters

### ISSUE THREAD

**Issue by Franky1** [tkrajina/gpxpy#91]
class GPXWaypoint: `__init__` is missing some GPX parameters: 
link, source... maybe some more...
Should be added in the `__init__(... , link=None, source=None, ...   ) `

**Comment by nawagers** [comment]
@Franky1 All the params are initialized in __init__(). Is the issue that you want a one-liner? Only about half the params are in the function call and the others would currently have to be set after initialization.

**Comment by Franky1** [comment]
Yes, i wanted a one-liner, but it is also okay to set them after initialization.
So we can close this issue.
