### ISSUE TITLE
gpx.adjust_times does not adjust waypoints

### ISSUE THREAD

**Issue by wrohdewald** [tkrajina/gpxpy#93]
Well - it does exactly what the docstring says - so it is actually correct.

But it makes the gpx file in its entirety inconsistent, users have to remember that they also need to adjust waypoints and maybe other places where there are times.

It is also inconsistent within the API: gpx.move will move tracks, routes, waypoints - so why shouldn't adjust_time also adjust all of them?

Changing that would be an incompatible change but I still think it would be a good idea.

**Comment by tkrajina** [comment]
Yes, this would make the API backward incompatible, but what we can do is to change from:

    def adjust_time(self, delta):

...to...

    def adjust_time(self, delta, all=None):

If `all` is `True` it would do what you expected.

If somebody is willing to implementing it (including tests), pull requests are welcome.

**Comment by vmarceau** [comment]
I will try to do it and send a PR.

**Comment by vmarceau** [comment]
PR sent.

**Comment by vmarceau** [comment]
I think this issue can be closed.

**Comment by tkrajina** [comment]
Right, thanks!
